# Generated by Django 4.2.5 on 2023-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_blogpost_image_alter_blogpost_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
