# Generated by Django 4.2.5 on 2023-09-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_blogpost_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost", old_name="image", new_name="picture",
        ),
    ]
